//define constants

const https = require('https');
const url = require('url');
const fs = require('fs');
//const db = require('F:/Jonas/Programme/Node JS/node_modules/mysql');


const ORDER_ID_CONST = 12;

module.exports = {
  ORDER_ID_LENGTH : ORDER_ID_CONST,
  MAIL_TRANSPORT : {
    service : 'gmail',
    auth : {
      user : 'jonas.seng1@gmail.com',
      pass : '&H?tW0_p2Ndq'
    }
  },
  MAIL_ADDR : 'jonas.seng1@gmail.com',
  ORDER_MAIL_SUBJECT : 'Bestellbestätigung',
  REG_MAIL_SUBJECT : 'Authentifizierung',
  PW_MAIL_SUBJECT : 'Ihr Passwort wurde geändert!',
  REG_MAIL_URL : 'https://localhost:3000/auth?id=',
  LOGGER_LOG_ERR : '[LOGGER ERR]',
  LOGGER_MAIL_ERR : '[MAIL ERR]',
  LOGGER_MAIL_SUCC : '[MAIL SENT]',
  LOGGER_ORDER_ERR : '[ORDER ERR]',
  LOGGER_ORDER_SUCC : '[ORDER OK]',
  LOGGER_GET_PROD_ERR : '[GET PRODUCT ERROR]',
  LOGGER_GET_ORDER_ERR : '[GET ORDER ERROR]',
  LOGGER_GET_USER_ERR : '[GET USER ERROR]',
  LOGGER_GET_ORDER_DETAILS_ERR : '[GET ORDER DETAILS ERROR]',
  LOGGER_GET_ORDER_DETAILS_SUCC : '[GET ORDER DETAILS OK]',
  LOGGER_GET_ORDER_DETAILS_TRY : '[GET ORDER DETAILS TRIAL]',
  LOGGER_GET_PREORDER_ERR : '[GET PREORDER ERROR]',
  LOGGER_GET_PREORDER_DETAILS_ERR : '[GET PREORDER DETAILS ERROR]',
  LOGGER_GET_PREORDER_DETAILS_SUCC : '[GET PREORDER DETAILS OK]',
  LOGGER_GET_PREORDER_DETAILS_TRY : '[GET PREORDER DETAILS TRIAL]',
  LOGGER_DESCR_ERR : '[DESCRIPTION ERROR]',
  LOGGER_REG_ERR : '[REGISTRATION ERR]',
  LOGGER_REG_SUCC : '[REGISTRATION OK]',
  LOGGER_LOGIN_ERR : '[LOGIN ERR]',
  LOGGER_LOGIN_SUCC : '[LOGIN OK]',
  LOGOIN_LOGOUT_ERR : '[LOGOUT ERR]',
  LOGGER_LOGOUT_SUCC : '[LOGOUT OK]',
  LOGGER_DEL_PREORDER_ERR : '[DELETE PREORDER ERR]',
  LOGGER_DEL_PRERORDER_SUCC : '[DELETE PREORDER OK]',
  LOGGER_DEL_PREORDER_TRY : '[DELETE PREORDER TRIAL]',
  LOGGER_DEL_ORDER_ERR : '[DELETE PREORDER ERR]',
  LOGGER_DEL_RORDER_SUCC : '[DELETE PREORDER OK]',
  LOGGER_DEL_ORDER_TRY : '[DELETE PREORDER TRIAL]',
  LOGGER_DEL_PRODUCT_ERR : '[DELETE PRODUCT ERR]',
  LOGGER_DEL_PRODUCT_SUCC : '[DELETE PRODUCT OK]',
  LOGGER_DEL_PRODUCT_TRY : '[DELETE PRODUCT TRIAL]',
  LOGGER_ADD_PRODUCT_ERR : '[ADD PRODUCT ERROR]',
  LOGGER_ADD_PRODUCT_SUCC : '[ADD PRODUCT OK]',
  LOGGER_ADD_PRODUCT_TRY : '[ADD PRODUCT TRIAL]',
  LOGGER_UPDATE_PRODUCT_ERR : '[UPDATE PRODUCT ERROR]',
  LOGGER_UPDATE_PRODUCT_SUCC : '[UPDATE PRODUCT OK]',
  LOGGER_UPDATE_PRODUCT_TRY : '[UPDATE PRODUCT TRIAL]',
  LOGGER_CONFIRM_ERR : '[CONFIRMATION ERR]',
  LOGGER_ADMIN_CONFIRM_ERR : '[ADMIN CONFIRMATION ERROR]',
  LOGGER_ADMIN_CONFIRM_SUCC : '[ADMIN CONFIRMATION OK]',
  LOGGER_ADMIN_CONFIRM_TRY : '[ADMIN CONFIRMATION TRIAL]',
  LOGGER_NEW_PASS_TRY : '[NEW PASSWORD TRIAL]',
  LOGGER_NEW_PASS_ERR : '[NEW PASSWORD ERROR]',
  LOGGER_NEW_PASS_OK : '[NEW PASSWORD OK]',
  LOGGER_FINISH_ERR : '[FINISH ERROR]',
  LOGGER_FINISH_TRY : '[FINISH TRIAL]',
  LOGGER_SEARCH_ERR : '[SEARCH ERROR]',
  LOGFILE_PATH : '../HTTPSServer/log.txt'
}
